table raw_titles
	lineageTag: 5953cf93-2cf4-4e20-8ef8-8f4efdeca49f

	column id
		dataType: string
		lineageTag: 28c9d5dd-4919-41ed-baf2-a50203cb5842
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column title
		dataType: string
		lineageTag: 9dacd911-88e0-4743-8e5a-d22b5da72061
		summarizeBy: none
		sourceColumn: title

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: cf2dd443-3a7f-4a8d-81a9-f3af4b514fab
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column release_year
		dataType: int64
		formatString: 0
		lineageTag: 7e4774bf-e459-441e-8fc3-2f65e8b2bed0
		summarizeBy: sum
		sourceColumn: release_year

		annotation SummarizationSetBy = Automatic

	column age_certification
		dataType: string
		lineageTag: e5347fe9-ee3c-4361-aa7e-a6432fa5228b
		summarizeBy: none
		sourceColumn: age_certification

		annotation SummarizationSetBy = Automatic

	column runtime
		dataType: int64
		formatString: 0
		lineageTag: 6494c234-c782-4084-9152-923dcb10165a
		summarizeBy: sum
		sourceColumn: runtime

		annotation SummarizationSetBy = Automatic

	column genres
		dataType: string
		lineageTag: 6e609ee2-6055-42c5-9701-a858c9b2707e
		summarizeBy: none
		sourceColumn: genres

		annotation SummarizationSetBy = Automatic

	column production_countries
		dataType: string
		lineageTag: e1bc5a7e-b86d-4f07-a8b5-d46f7f5d56a0
		summarizeBy: none
		sourceColumn: production_countries

		annotation SummarizationSetBy = Automatic

	column seasons
		dataType: int64
		formatString: 0
		lineageTag: 79b541b5-5e72-4e17-80d9-4a617bb69eca
		summarizeBy: sum
		sourceColumn: seasons

		annotation SummarizationSetBy = Automatic

	column imdb_id
		dataType: string
		lineageTag: 7e281ae2-03fb-4e98-8c23-7c1e9d96a7f4
		summarizeBy: none
		sourceColumn: imdb_id

		annotation SummarizationSetBy = Automatic

	column imdb_score
		dataType: double
		lineageTag: f1f5a329-2d66-44b8-8215-9a49aae6bca3
		summarizeBy: sum
		sourceColumn: imdb_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column imdb_votes
		dataType: int64
		formatString: 0
		lineageTag: 7761b275-a4e8-4da3-93fe-635e96fff246
		summarizeBy: sum
		sourceColumn: imdb_votes

		annotation SummarizationSetBy = Automatic

	partition raw_titles = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Karthik\Desktop\PBI Git integration practise\Dataset\Netflix movies and series\raw_titles.csv"),[Delimiter=",", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id", type text}, {"title", type text}, {"type", type text}, {"release_year", Int64.Type}, {"age_certification", type text}, {"runtime", Int64.Type}, {"genres", type text}, {"production_countries", type text}, {"seasons", Int64.Type}, {"imdb_id", type text}, {"imdb_score", type number}, {"imdb_votes", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

